title: Weather app
description: Complete weather app which has been build on node and react
template:
  repo: weather-app-template
  name: weather-app
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
